apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: gerlacdt/helloapp:v0.5.0
        name: hello
        securityContext:
          capabilities:
            drop: ["all"]
            add: ["NET_BIND_SERVICE"]
          runAsUser: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        env:
          - name: NOMAD_PORT_http
            value: "8080"
        ports:
        - containerPort: 8080
          protocol: TCP
