apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello
  name: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: hello
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: hello
        environment: {{ .Values.environment }}
    spec:
      containers:
      - image: {{ .Values.container.image }}:{{ .Values.container.tag }}
        name: {{ .Values.container.name }}
        securityContext:
          capabilities:
            drop: ["all"]
            add: ["NET_BIND_SERVICE"]
          runAsUser: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        env:
          - name: NOMAD_PORT_http
            value: "8080"
          - name: MAGIC_WORD
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: magicWord
        ports:
        - containerPort: 8080
          protocol: TCP
