apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}
spec:
  selector:
    app: hello
    environment: {{ .Values.environment }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
